#mysql-dev
spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://dev-lms.cq6gbzb8eeqc.us-west-1.rds.amazonaws.com:3306/lingoace_lms_package?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
          username: lingoace-lms
          password: clmdxoVgR7RD

  rabbitmq:
    username: test-lingoace
    password: PjGXedss!HOfz7#BHD2oM8
    virtual-host: test-lingoace
    addresses: 54.219.244.229:13334

log:
  path: /data/logs/edu/cloudDisk

client:
  pub-studentcenter-host: http://10.1.4.225:8400
  teacher-manage-host: http://10.1.4.225:9001
  pub-usercent-host: http://10.1.4.225:8405

